ENTITY_TYPE_AUTH = "auth"
ENTITY_TYPE_SESSION = "session"
ENTITY_TYPE_USER = "user"
ENTITY_TYPE_DOCUMENT = "document"
ENTITY_TYPE_MESSAGE = "message"
ENTITY_TYPE_ORDER = "order"
ENTITY_TYPE_INVENTORY = "inventory"
ENTITY_TYPE_PRODUCT_REGISTRATION = "product_registration"
ENTITY_TYPE_PRODUCT = "product"

EVENT_TYPE_AUTH_LOGIN_FAILED = "auth.login.failed"
EVENT_TYPE_AUTH_LOGIN_SUCCEEDED = "auth.login.succeeded"
EVENT_TYPE_AUTH_REFRESH_SUCCEEDED = "auth.refresh.succeeded"
EVENT_TYPE_AUTH_LOGOUT_CURRENT = "auth.logout.current"
EVENT_TYPE_AUTH_LOGOUT_ALL = "auth.logout.all"

EVENT_TYPE_USER_BOOTSTRAP = "user.bootstrap"
EVENT_TYPE_USER_REGISTER = "user.register"
EVENT_TYPE_USER_CREATE = "user.create"
EVENT_TYPE_USER_UPDATE = "user.update"
EVENT_TYPE_USER_DELETE = "user.delete"

EVENT_TYPE_DOCUMENT_CREATE = "document.create"
EVENT_TYPE_DOCUMENT_UPDATE = "document.update"
EVENT_TYPE_MESSAGE_CREATE = "message.create"
EVENT_TYPE_MESSAGE_UPDATE = "message.update"
EVENT_TYPE_MESSAGE_DELETE = "message.delete"
EVENT_TYPE_ORDER_CREATE = "order.create"
EVENT_TYPE_ORDER_UPDATE = "order.update"
EVENT_TYPE_ORDER_DELETE = "order.delete"
EVENT_TYPE_ORDER_COMMENT_CREATE = "order.comment.create"
EVENT_TYPE_INVENTORY_CREATE = "inventory.create"
EVENT_TYPE_INVENTORY_UPDATE = "inventory.update"
EVENT_TYPE_PRODUCT_REGISTRATION_CREATE = "product_registration.create"
EVENT_TYPE_PRODUCT_REGISTRATION_UPDATE = "product_registration.update"
EVENT_TYPE_PRODUCT_CREATE = "product.create"
EVENT_TYPE_PRODUCT_UPDATE = "product.update"
EVENT_TYPE_PRODUCT_DELETE = "product.delete"